### ISSUE TITLE
CLI does not work on python 2.7 (or 3?)

### ISSUE THREAD

**Issue by bendikro** [devilry/devilry-django#85]
When logging in, the following error is given:
AttributeError: HTTPSConnection instance has no attribute 'getreply'
